### ISSUE TITLE
H-alpha filters

### ISSUE THREAD

**Issue by keflavich** [abulatek/paschen-alpha#1]
https://github.com/abulatek/paschen-alpha/blob/ac37418915587f019fd26dcdb8cdd525cf80383d/ccd_script.py#L53

can use 
http://svo2.cab.inta-csic.es/theory/fps/index.php?id=INT/IPHAS.Ha&&mode=browse&gname=INT&gname2=IPHAS#filter

**Comment by keflavich** [comment]
https://www.eso.org/sci/facilities/paranal/instruments/omegacam/inst.html zero point is absent though

**Comment by abulatek** [comment]
Thanks! I ended up using the result from SVO-FPS that you linked above.
