### ISSUE TITLE
can't add units to dataframes

### ISSUE THREAD

**Issue by keflavich** [abulatek/paschen-alpha#2]
https://github.com/abulatek/paschen-alpha/blob/49fd9c984f20cb90e79956f135bf346db0bb7299/ccd_combined.py#L36

should be 
`yso_FHa_flux = u.Quantity(df_yso_grouped['FHa'].agg(np.mean), u.erg/u.s/u.cm**2)`
(though your units were correct - you could use a unit of `1e-3 W/m^2`)

The same `u.Quantity(array, unit)` needs to be applied to the rest of the lines too

**Comment by abulatek** [comment]
Should be fixed now! Thank you for the information.
